[project]
authors = ["Jared Bard <jabard89@gmail.com>"]
channels = ["conda-forge","bioconda"]
description = "Python scripts to convert proprietary image files to ome-tiff"
name = "convert_to_ome"
platforms = ["osx-64","win-64","linux-64"]
version = "0.1.0"
license = "MIT"

[tasks]

[dependencies]
python = ">=3.11, <3.12"
scyjava = ">=1.12.0,<2"
pip = ">=24.3.1,<25"

[pypi-dependencies]
bioio = ">=3.0"
bioio-ome-tiff = ">=1.4.0"
bioio-nd2 = ">=1.3.0"
bioio-czi = ">=2.4.0"
bioio-lif = ">=1.4.0"
marimo = ">=0.15.0"
bioio-bioformats = ">=1.3.0"
requests = "*"
